import {test} from "@playwright/test"
test("test1",async({page})=>{
    await page.goto("https://vinothqaacademy.com/demo-site/")
    await page.locator('//label[@for="vfb-5"]').fill("tamanna")
    await page.locator('//label[@for="vfb-7"]').fill("singh")
    await page.locator('//li[@id="item-vfb-31"]')
    await page.locator('(//input[@class="vfb-radio  required  name"])[2]').click()
    await page.locator('//li[@id="item-vfb-20"]')
    await page.locator('//input[@id="vfb-20-1"]').click()
    await page.locator('//li[@class="vfb-item vfb-item-address  "]')
    await page.locator('//input[@id="vfb-13-address"]').fill("mohali")
    await page.locator('//input[@id="vfb-13-address-2"]').fill("2")
    await page.locator('//input[@id="vfb-13-city"]').fill("mohali")
    await page.locator('//input[@id="vfb-13-state"]').fill("punjab")
    await page.locator('//input[@id="vfb-13-zip"]').fill("140301")
    await page.locator('//select[@id="vfb-13-country"]').selectOption({value:"India"})
    await page.locator('//label[@for="vfb-14"]').fill("tamannasingh123@gmail.com")
    await page.locator('//label[@for="vfb-18"]').fill("18-04-26")
    await page.locator('//li[@id="item-vfb-16"]')
    await page.locator('//select[@id="vfb-16-hour"]').selectOption({value:"03"})
    await page.locator('//select[@id="vfb-16-min"]').selectOption({value:"20"})
    await page.locator('//label[@for="vfb-19"]').fill("91420441896")
    await page.locator('//label[@for="vfb-23"]').fill("nothing")
    await page.locator('//input[@id="vfb-3"]').fill("33")
    await page.getByRole('button',{name:"Submit"}).click()
})